import type { Metadata } from "next";
import { ubuntu, quicksand, roboto } from "@/fonts";
import "./globals.css";

// Collect all font variable classNames into one string
const fontClasses = [ubuntu.variable, quicksand.variable, roboto.variable].join(
  " "
);
export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontClasses} antialiased`}>{children}</body>
    </html>
  );
}
